
preset: 'optimal'

model:
    architecture: 'resnet18' 
    features: 100     # Number of encoded features (null just uses original resnet output)
    n_epochs: 600
    downscale: True
    m: 0.996 # Controls EMA hyperparameter for BYOL momentum encoder
    m_decay: False

projection_head:
    hidden: 1024
    out: 256

data:
    color_channels: 1
    classes: 2
    rotate: True
    input_height: 128 # Keep this at 128 and adjust center_crop_size
    pretrain_batch_size: 256
    val_batch_size: 500
    cut_threshold: 27
    test_frac: 0.3 

optimizer:
  type: 'sgd'
  lr: 0.06
  momentum: 0.9
  weight_decay: 0.0005 # 0.0005
  lars: False
  trust_coef: 0.003

scheduler:
  type: 'cosine' # ['none', 'cosine', 'warmupcosine']
  warmup_epochs: 10  # Only used in linear warmup cosine annealing, if scheduler type is 'warmupcosine'

linear:
    n_epochs: 50
    opt: 'adam'
    lr: 0.0003
    batch_size: 300
    momentum: 0
    nesterov: False
    weight_decay: 0

## DATA ## 
augmentations:
  center_crop_size: 80
  random_crop_scale: !!python/tuple [0.8, 1]
  p_radio: 0.5
  p_blur: 0
  blur_kernel: 3 # Odd non-integer number
  s: 0.5
  p_aug: 0.5
